#!/bin/bash

(("$#")) || exit 1

URL='https://api.datamuse.com'
QRY=("$@")
MAX=20
OFS=1
SEL=$1

mkdir -p /tmp/xsyn &>/dev/null || :

declare -A OPTS=(
  [ml]=ml
  [sn]=rel_syn
  [nn]=rel_jja
  [aj]=rel_jjb
)

grep -qv "$1" <<<"${!OPTS[@]}" && {
  SEL=ml
  OFS=0
}

I="${OPTS[$SEL]}"
Q="${I}=$(tr ' ' '+' <<<"${QRY[@]:$OFS}")"
U="${URL}/words?${Q}&max=$MAX"
J='.[].word|gsub("[ ]";"_")'

curl -s "$U" |
  jq '.' |
  tee /tmp/xsyn/raw.json |
  jq -r "$J" |
  tee /tmp/xsyn/fmt |
  column |
  yank -- xsel --clipboard --trim

# vim: ft=bash
